# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

title: Kyle Grover
email: kyle@kylegrover.com
google_tag_manager_id: 89386910-2
baseurl: "" # the subpath of your site, e.g. /blog
url: https://kylegrover.com # the base hostname & protocol for your site, e.g. http://example.com
port: 1234
github_username:  kylegrover
footer_copyright_text: Developed, designed, and hosted by Kyle Grover.
collections:
  - client_work

# Build settings
markdown: kramdown